// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR3ZLJB_qCY0hWBE_-lwSUFZKSHVeiL5U',
    appId: '1:1021231368408:web:d0eb88b95a39b0a99f2fad',
    messagingSenderId: '1021231368408',
    projectId: 'demote-91d58',
    authDomain: 'demote-91d58.firebaseapp.com',
    databaseURL: 'https://demote-91d58-default-rtdb.firebaseio.com',
    storageBucket: 'demote-91d58.appspot.com',
    measurementId: 'G-8QT865YCMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCXCiltqkqwabzh61u_MfeMLl1_pp-jQ',
    appId: '1:1021231368408:android:409707e63e6f22409f2fad',
    messagingSenderId: '1021231368408',
    projectId: 'demote-91d58',
    databaseURL: 'https://demote-91d58-default-rtdb.firebaseio.com',
    storageBucket: 'demote-91d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYrgVabNS9-K6ipE-8vH30kWyhp6fm4s',
    appId: '1:1021231368408:ios:f96271171cb597049f2fad',
    messagingSenderId: '1021231368408',
    projectId: 'demote-91d58',
    databaseURL: 'https://demote-91d58-default-rtdb.firebaseio.com',
    storageBucket: 'demote-91d58.appspot.com',
    iosClientId: '1021231368408-gc7dlm4kn2db9ooo101pv7g4ieprdc9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYrgVabNS9-K6ipE-8vH30kWyhp6fm4s',
    appId: '1:1021231368408:ios:f96271171cb597049f2fad',
    messagingSenderId: '1021231368408',
    projectId: 'demote-91d58',
    databaseURL: 'https://demote-91d58-default-rtdb.firebaseio.com',
    storageBucket: 'demote-91d58.appspot.com',
    iosClientId: '1021231368408-gc7dlm4kn2db9ooo101pv7g4ieprdc9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopController',
  );
}
